### ISSUE TITLE
水电查询

### ISSUE THREAD

**Issue by syit-yx** [longchengguxiao/nonebot_plugin_xdu_support#17]
你好，能否考虑添加水电查询功能，也就是内网的`http://10.168.55.50:8088`系统，感觉这个还是有需求的。
如果需要添加的话，我可以提供已测试的python脚本，我也完成了插件的基本开发，希望能整合到你这个项目中。

**Comment by longchengguxiao** [comment]
赵哥哥～快来提交一个pr吧。

**Comment by syit-yx** [comment]
卧槽秒回？

**Comment by syit-yx** [comment]
卧槽秒回，等我熟悉一下github，还没提过pr

**Comment by longchengguxiao** [comment]
> 卧槽秒回，等我熟悉一下github，还没提过pr
> 

这不正刷着手机呢嘛，顺手就回复了。先fork到本地，更新之后创新pr就行啦！
